my_dwh:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_POSTGRES_HOST', 'dwh-postgres') }}"
      port: "{{ env_var('DBT_POSTGRES_PORT', '5432') | int }}"
      user: "{{ env_var('DWH_POSTGRES_USER', 'dwh') }}"
      password: "{{ env_var('DWH_POSTGRES_PASSWORD', 'dwh') }}"
      dbname: "{{ env_var('DWH_POSTGRES_DB', 'dwh') }}"
      schema: public
      threads: 4
